### ISSUE TITLE
森林管理計画書の影響範囲

### ISSUE THREAD

**Issue by thisismytestaccount334** [hyakumori/Nishiawakura_FM_Documents#5]
具体的にどの範囲をこの管理計画書では対象にしているのですか？

**Comment by tabatasunao** [comment]
イシュー作成用のデモ質問だけど一応回答

> 対象
> 　本計画書の対象は、「百年の森林事業」にて長期的な施業管理の委託を受けた森林とする。「百年の森林事業」は「百年の森林構想」の下に行われる村の事業であり、森林整備から製材や木材加工までを一体的に村内で循環させることで、長期にわたり安定的な森林管理を可能とするものである。管理区域の地図は「西粟倉森林管理地図」として閲覧できる。
