### ISSUE TITLE
山守とコラボ

### ISSUE THREAD

**Issue by yuntas** [hyakumori/Nishiawakura_FM_Documents#6]
[https://www.yamamori.online/?gclid=CjwKCAjwzOqKBhAWEiwArQGwaDW9cx5hXmhDVTdzbVNQosOnvnC_aJHOjWBGQY9YrDsi0KqRqwEA4RoC6hUQAvD_BwE](https://www.yamamori.online/?gclid=CjwKCAjwzOqKBhAWEiwArQGwaDW9cx5hXmhDVTdzbVNQosOnvnC_aJHOjWBGQY9YrDsi0KqRqwEA4RoC6hUQAvD_BwE)

**Comment by tabatasunao** [comment]
実はこの管理計画書を管理している株式会社百森は、山守 YAMAMORIとも提携しています！ウェブサイト下段「提携・協力企業」をご覧ください。

管理計画書的には外部の利用・活用に向けた方法をどう盛り込んでいくか、という課題がありますね。

**Comment by yuntas** [comment]
@tabatasunao ちゃんと拝読せぬまま、失礼いたしました（汗

私自身も先祖からの山林があるという事を祖母や父から聞く程度で
何ができるのか、これから引き継いだ後はどうしたらいいのか門外漢で不安と
漠然とですが携わりたいという思いもあり、山について、木について、林業について
少しずつ知る所から始めていこうと思っているのが現状です。

国土の2/３が山林で、水も豊か、ジビエや山菜も豊か、
しかし木材は輸入材に追いやられているんですよね。。。

**Comment by tabatasunao** [comment]
有難うございます！山林はなかなか関わりしろが難しいところですね。そういう意味でも、いろいろとオープンにしていければと思っています！引き続き宜しくお願いします。いったんこのIssueはクローズします。
